### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by Crote** [brandur/sorg#157]
As [heinrichhartman stated on HN](https://news.ycombinator.com/item?id=15297587), your websites is one of the few programming-related blogs which has managed to be beautifully typeset. I, and probably some others with me, would like to re-use some of the css used to obtain this look.

While this repository is quite helpful in order to understand how the final product is created, the lack of a licence means that [nobody is allowed to re-use any part of it](https://help.github.com/articles/licensing-a-repository/). Would you consider releasing (some part of) this repository under an open-source licence?

**Comment by brandur** [comment]
Hi @Crote, thanks for the kind words!

I've added an MIT license in 224a133.

Of course, it'd be better if the site's design wasn't copied wholesale, but I have no qualms about people using particular pieces, ideas, or inspiration.

There are a few images that I've included in the repository which are someone else's copyright and which the MIT license won't apply to. All of those are appropriately attributed (usually in the corresponding article's YAML frontmatter), but keep an eye out.
