### ISSUE TITLE
Webhooks alternative: gRPC

### ISSUE THREAD

**Issue by amitsaha** [brandur/sorg#164]
Hello, i asked on Twitter (but probably wasn't the best forum for doing so). In your post, you mention gRPC's streaming as a possible alternative to webhooks. I wasn't quite sure what you meant by that. Would it possible for you to explain that a bit more? 

Thanks for the post and I find all your articles very insightful! 👍

**Comment by brandur** [comment]
Hi Amit,

Sorry about the lack of Twitter response — unfortunately I don't track that as an incoming stream all that carefully (it's pretty hard to give meaningful responses most of the time anyway).

So GRPC is Google's framework for making RPC calls (basically invoking functions on a server from a client) using Protobufs and HTTP. In particular for this case we're interested in [server-side streaming](https://grpc.io/docs/guides/concepts.html#server-streaming-rpc).

Note that there's a distinction between client and server-side here. Client streaming is when a client sends up a stream to the server, and server streaming is the opposite — a client opens a connection, and a server streams information back to it.

Google does a pretty nice job with examples. See [`route_guide` as a demonstration of what it looks like](https://github.com/grpc/grpc-go/tree/master/examples/route_guide). In particular, [here's the code for a server to stream information to a client](https://github.com/grpc/grpc-go/blob/5a82377e69857eae7e2de0b451668f3cf18d5a31/examples/route_guide/server/server.go#L138-L142) and [here's the code for a client to process that stream](https://github.com/grpc/grpc-go/blob/5a82377e69857eae7e2de0b451668f3cf18d5a31/examples/route_guide/client/client.go#L111-L135).

I hope that helps. Thanks for reading!

**Comment by amitsaha** [comment]
No problems and Thanks for the reply :+1: I have been reading up on gRPC recently and learned a bit about the client side and server side streaming. What I was more keen on learning is how you think we could use that feature as alternative to webhooks?

**Comment by brandur** [comment]
> What I was more keen on learning is how you think we could use that feature as alternative to webhooks?

GRPC isn't a perfect symmetry for webhooks, but if squint a little, they both look pretty close.

If you think about why webhooks are useful, it's really their "streaming" aspect. A common REST API offers nice features for polling, but a webhooks API is able to stream changes that only the server is aware of back to the client.

You can think of GRPC streams as a technology that can do something similar. With a webhook, a client registers one of their endpoints and receives updates to it from the server. With a GRPC stream, a client would connect to the server and receive a list of changes back from it over a long-lived connection. Same idea as long polling on the web.

**Comment by amitsaha** [comment]
> You can think of GRPC streams as a technology that can do something similar. With a webhook, a client registers one of their endpoints and receives updates to it from the server. With a GRPC stream, a client would connect to the server and receive a list of changes back from it over a long-lived connection. Same idea as long polling on the web.

Thanks, that's what I wanted to know. I will close the issue. In future, I will open an issue to seek further clarification :+1:

**Comment by brandur** [comment]
NP and sounds good! Will talk you then.
