### ISSUE TITLE
Question: pool

### ISSUE THREAD

**Issue by damianoneill** [brandur/sorg#195]
Reading your article https://brandur.org/go-worker-pool, its unclear to me how a Task in your pool implementation should return a computed value.  I have seen other implementations where the Task signature is a func returning an interface{}, error.  I guess in your solution that you expect the Task func to pass in an address?  

Can you elaborate your example to show how this should be handled?  

```
tasks := []*Task{
    NewTask(func() error { return nil }),
    NewTask(func() error { return nil }),
    NewTask(func() error { return nil }),
}

p := pool.NewPool(tasks, conf.Concurrency)
p.Run()

var numErrors int
for _, task := range p.Tasks {
    if task.Err != nil {
        log.Error(task.Err)
        numErrors++
    }
    if numErrors >= 10 {
        log.Error("Too many errors.")
        break
    }
}
```

For e.g. if each Task creates a Result and these are stored in a 

```
var results []Result
```

**Comment by brandur** [comment]
This might be a slightly suboptimal answer because I haven't thought about it in a while, but since we're storing an error on `Task` already anyway, it probably also makes sense to just put the result there as well:

``` go
type Task struct {
	Err error
	Result interface{}
	f func() (interface{}, error)
}

func (t *Task) Run(wg *sync.WaitGroup) {
	t.Result, t.Err = t.f()
	wg.Done()
}
```

It's not great that you have to fall back to `interface{}` for this though ... it might be worthwhile seeing if you could build some task-specific shims on top of `Task` whose only job is to transform `interface{}` back to something more material.

**Comment by damianoneill** [comment]
Thanks @brandur so something like 

```
	tasks := []*pool.Task{
		pool.NewTask(func() (interface{}, error) { return nil, nil }),
		pool.NewTask(func() (interface{}, error) { return true, nil }),
		pool.NewTask(func() (interface{}, error) { return 20, nil }),
		pool.NewTask(func() (interface{}, error) { return time.Now(), nil }),
	}
```

And if the Task has to be parameterised assume the signature would need to change to use a variadic interface? 

```
func(a ...interface{}) (interface{}, error)
```

**Comment by brandur** [comment]
> Thanks @brandur so something like

No worries. And yes — that looks right.

> And if the Task has to be parameterised assume the signature would need to change to use a variadic interface?

It's mostly up to your preference again. You could also add your arguments into `Task` again:

``` go
type Task struct {
	Args []interface{} 
	Err error
	Result interface{}
	f func() (interface{}, error)
}
```

Alternatively, remember that those `func()` are closures and can capture variables from their surrounding environment. You could also inject data that way:

``` go
arg1 := ...
arg2 := ...
pool.NewTask(func() (interface{}, error) {
	fmt.Printf("%v %v\n", arg1, arg2)
	return nil, nil
}),
```

**Comment by damianoneill** [comment]
Thanks, new to go, just finished reading up on closures and scope, your proposal makes perfect sense.  Appreciate the response.  

Damian.
