### ISSUE TITLE
&mdash; is not being displayed as –

### ISSUE THREAD

**Issue by JuanitoFatas** [brandur/sorg#200]
Hello Brandur,

I notice your posts have `&mdash;` instead of &mdash;.

<img width="533" alt="screenshot 2018-07-30 00 58 16" src="https://user-images.githubusercontent.com/1000669/43378261-b7e78e34-9393-11e8-8105-2431284b9abc.png">

- https://brandur.org/fragments/aws-static-hosting

<img width="545" alt="screenshot 2018-07-30 00 58 36" src="https://user-images.githubusercontent.com/1000669/43378265-bd3ed2de-9393-11e8-99a5-39e8a8c0a5c2.png">

- https://brandur.org/fragments/2015-update

Wondering if you need to [configure special chars](https://s3-eu-west-1.amazonaws.com/affinity-docs/help/designer/English.lproj/index.html?page=/Text/specialCharacters.html?title=Special%20characters) on S3.

Cheers,
Juanito

**Comment by brandur** [comment]
Well, that's pretty embarrassing!

I think this must have broken when I moved from Ruby to Go and semantics in the Markdown renderer I was using shifted slightly. I'm pretty surprised I never noticed before though! Weird.

I'm fixing in #201 by just replacing instances of "&mdash;" with "--" — this is my convention these days anyway, it's converted to a real emdash when rendered, and it's more readable when looking at the Markdown as plaintext.

Thanks for the report Juanito! Nice to see you drop by.
