### ISSUE TITLE
Broken URL with parentheses

### ISSUE THREAD

**Issue by cippaciong** [brandur/sorg#265]
Hi, I was ~~binge-reading~~ casually browsing through your website, and I noticed that at the end of the [about](https://brandur.org/about#design) page, the link to the Wikipedia page for Helvetica is broken, probably due to an incorrect parsing of the parentheses in the URL.

Congrats for your work by the way 🙂. I love the content of your blog and newsletters, and your approach to technological challenges in general!

**Comment by brandur** [comment]
@cippaciong Thank you for the kind words! Glad you enjoyed some of it :)

Great catch on that bad link. I think this happened recently as I converted a bunch of pages from Ace format into Markdown. Fixed with an escape in 959a4bef.
