### ISSUE TITLE
ffmpeg-h265 quicktime playback of 5.1 aac

### ISSUE THREAD

**Issue by thpryrchn** [brandur/sorg#267]
it can be done!!!! All you need is '-channel_layout 5.1' for some reason, if ffmpeg sees a source as ' 5.1(side)', the resulting mp4 will not play on Apple Quicktime. But by changing it to 5.1, it works.

I couldn't just make a commit to your md

**Comment by brandur** [comment]
@thpryrchn Wow crazy! Let me give that a shot later. It'll be nice not to feel like I'm encoding my audio with a stone age codec :) I'll update the article once I've seen it for myself. Thanks for the report!

**Comment by brandur** [comment]
Nice, it seemed to work for me. Updated the article with multi-channel AAC instructions in 546134f8. Thanks again.
