### ISSUE TITLE
Unable to horizontally scroll code blocks on mobile

### ISSUE THREAD

**Issue by bnjmnt4n** [brandur/sorg#280]
Using Firefox and Chrome on Android, I'm unable to horizontally scroll code blocks.

**Comment by brandur** [comment]
Hmm, I don't have an Android device unfortunately, but I've tried repro'ing on my i* devices and in Chrome's Android mode from Dev Tools, and can't seem to be repro.

Can you send a specific page you're having trouble with? Some of the different pieces are styled differently, so it might matter.

**Comment by bnjmnt4n** [comment]
Looking at https://brandur.org/text, I realized the behaviour I'm seeing is quite inconsistent. On Firefox, I can't seem to scroll the first code block (beginning with `CREATE DOMAIN text_standard`). However, I can scroll the other two code blocks below that, but only partially: the ends of the two code blocks are still hidden. I think it might be hard to reproduce this issue from DevTools. I'll update here if I've got more time to look into this.

Also, huge thanks for your articles and newsletters, they've been very engaging and technically interesting!

**Comment by bnjmnt4n** [comment]
Actually, I was able to reproduce this on Firefox desktop by reducing the browser width. Removing the following rule on `pre, pre[class*="language-"]`: `width: calc(650px - 2 * 25px);` restored proper scrollbar behaviour.

**Comment by brandur** [comment]
Huh, that's weird! I went back to that article and was even able to repro the problem in Chrome with no Dev Tools involved.

> Maybe a media query to avoid setting explicit widths on smaller screen sizes would do the trick.

Good catch. And yep, that fixes the issue. Just committed 4fe1474f732eec313ba57d16ed701c20249d5aca.

> Also, huge thanks for your articles and newsletters, they've been very engaging and technically interesting!

NP and thanks for reading!
