### ISSUE TITLE
Transactionally Staged Job Drains in Postgres - Sidekiq extension

### ISSUE THREAD

**Issue by adamniedzielski** [brandur/sorg#291]
Hey, thanks a lot for writing https://brandur.org/job-drain 💛 I keep coming to the article every now and then. Based on your suggestions I implemented https://github.com/adamniedzielski/sidekiq-staged_push. Would you consider mentioning the gem at the end of the article?

**Comment by brandur** [comment]
Adam — sorry for the delayed response, my email is a mess nowadays. Sure, no problem. Pushed in ed4fc953.

**Comment by adamniedzielski** [comment]
Thank you 💛

**Comment by adamniedzielski** [comment]
@fractaledmind you may be interested as well 😉
