### ISSUE TITLE
Close defer snippet incorrect for http retry?

### ISSUE THREAD

**Issue by jeff303** [brandur/sorg#316]
Hi, this is regarding the "A simple HTTP retry and backoff loop in Go" article [here](https://brandur.org/fragments/go-http-retry).  The code snippet currently has

```go
func getURLData(url string) (*http.Response, []byte, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, nil, err
	}
	defer body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, nil, err
	}

	return resp, body, nil
}
```

But I think that the `defer` should be called on `resp.Close()`, right?  The `body` var is not declared yet at that point (and besides, once it's initialized, it's the byte array).  I'm not a Golang expert so I could be wrong here.

**Comment by brandur** [comment]
Thanks Jeff — yep, I messed this up after someone pointed out a forgotten defer. Should actually be `defer resp.Body.Close()`. Fixed in 4bb95a0a.
