### ISSUE TITLE
"View all atoms" button on atom detail screen ignores theme toggle in dark theme

### ISSUE THREAD

**Issue by aghdom** [brandur/sorg#363]
Basically what the title says. Not necessarily a "major usability issue", but I noticed this small omission and thought I'd let you know. 

Here's an image for reference:
![image](https://github.com/brandur/sorg/assets/22467179/3286ea57-3601-46b4-9992-0d44e3f0c904)

**Comment by brandur** [comment]
Absolutely right. Fixed in f821b550.

I appreciate you taking the time to file a report. Thank you!
