### ISSUE TITLE
"Sqlc: 2024 check in" update query example can be simplified a lot

### ISSUE THREAD

**Issue by echarrod** [brandur/sorg#371]
Hello 👋 

I enjoyed reading your [Sqlc: 2024 check in](https://brandur.org/fragments/sqlc-2024) article.

I believe I've identified a large improvement on your example. Your update query example can be simplified a lot, as I had the same concerns as you originally, and found that sqlc has [nullable parameters](https://docs.sqlc.dev/en/stable/howto/named_parameters.html#nullable-parameters), that you can use with COALESCE to make the queries a lot more concise.
```sql
-- name: UpdateAuthor :one
UPDATE author
SET
 name = coalesce(sqlc.narg('name'), name),
 bio = coalesce(sqlc.narg('bio'), bio)
WHERE id = sqlc.arg('id')
RETURNING *;
```

So in your example e.g.
```sql
    archived_at = CASE WHEN @archived_at_do_update::boolean THEN @archived_at ELSE archived_at END,
```
Instead of setting and passing in `archived_at_do_update`as a param for each of your fields, you can do:
```sql
    archived_at = COALESCE(sqlc.narg('archived_at'), archived_at),
   ...
```

Wasn't sure if you wanted to update or not, so didn't want to fork and raise a MR

**Comment by brandur** [comment]
Thx. The trouble with the use of coalesce/sqc.narg is that it doesn't allow you to set an explicit `NULL`.

So it's fine if you're trying to move a value from null -> not null, but you can't then go back the other direction because the `NULL` always gets coalesced back to the existing value. Setting `NULLs` does turn out to be required in quite a few cases.

**Comment by echarrod** [comment]
> So it's fine if you're trying to move a value from null -> not null, but you can't then go back the other direction because the `NULL` always gets coalesced back to the existing value. Setting `NULLs` does turn out to be required in quite a few cases.

Ah OK. Yes sorry, I guess this worked in my scenario as I wasn't wanting to allow `NOT NULL` -> `NULL`!

I guess the params and monster snippet is required if you need to do that then 😁

**Comment by brandur** [comment]
Yeeaaaa, unfortunately I think it's the only way. Hopefully some new innovation in sqlc core eventually makes all this stuff unnecessary.
